backend:
  name: github
  repo: eddcp/edupaivadev.com
  base_url: https://edupaivadev-com.vercel.app
  auth_endpoint: api/auth/
  branch: main

local_backend: true

publish_mode: editorial_workflow # Isso permite ter aquele workflow com drafts e tudo
slug:
  encoding: 'ascii'
  clean_accents: true

media_folder: public/img
public_folder: /img

collections:
  - name: posts # Used in routes, e.g., /admin/collections/blog
    label: posts # Used in the UI
    folder: posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: 'YYYY-MM-DD hh:mm:ss'}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}